server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ecobank/ {
    proxy_pass https://apimuat-gateway.ecobank.com/;
    proxy_set_header Host apimuat-gateway.ecobank.com;
    proxy_set_header Origin https://apimuat-gateway.ecobank.com;
    proxy_ssl_server_name on;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}